site_name: Federated Learning
site_author: Mathieu Klimczak
theme:
  name: material
  logo: images/noun_Robot_1955251.svg
  language: fr
  features:
    - navigation.instant
    - navigation.tabs


plugins:
  - search:
      lang: fr
  #- mkdocs-jupyter

nav:
  - Acceuil: index.md
  - Module:
    - Th√©orie: Module.md


markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - attr_list

  # config pour latex
  - pymdownx.arithmatex:
      generic: true


# config pour latex
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
